# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_vhdl -library xil_defaultlib C:/Users/Pierre-Olivier/Documents/GitHub/Projet_horloge/project_H/project_H.srcs/sources_1/new/transcodeur_7_seg.vhd
read_xdc C:/Users/Pierre-Olivier/Documents/GitHub/Projet_horloge/project_H/project_H.srcs/constrs_1/imports/contrainte/decodeur_hexa_7seg.xdc
set_property used_in_implementation false [get_files C:/Users/Pierre-Olivier/Documents/GitHub/Projet_horloge/project_H/project_H.srcs/constrs_1/imports/contrainte/decodeur_hexa_7seg.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Pierre-Olivier/Documents/GitHub/Projet_horloge/project_H/project_H.cache/wt [current_project]
set_property parent.project_dir C:/Users/Pierre-Olivier/Documents/GitHub/Projet_horloge/project_H [current_project]
catch { write_hwdef -file transcodeur_7_seg.hwdef }
synth_design -top transcodeur_7_seg -part xc7a35tcpg236-1
write_checkpoint transcodeur_7_seg.dcp
report_utilization -file transcodeur_7_seg_utilization_synth.rpt -pb transcodeur_7_seg_utilization_synth.pb
